# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# on:
#   push:
#     tags:
#       - 'v*.*.*'
#   workflow_dispatch:

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21 (Zulu)
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'zulu'
        cache: maven

    # - name: Configure Git
    #   run: |
    #     git config --global user.name 'Your Name'
    #     git config --global user.email 'your-email@example.com'

    - name: Set up Maven settings
      run: |
        mkdir -p ~/.m2
        echo "<settings><servers><server><id>github</id><username>${{ secrets.GITHUB_ACTOR }}</username><password>${{ secrets.GITHUB_TOKEN }}</password></server></servers></settings>" > ~/.m2/settings.xml

    - name: Build with Maven (Clean)
      run: mvn clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build with Maven (Verify)
      run: mvn verify
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build with Maven (Package) #Optional
      run: mvn -B package --file springboot-deploy/pom.xml

    - name: Prepare release
      run: mvn release:prepare -B
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Perform release
      run: mvn release:perform -B
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: Deploy to Maven Central
    #   run: mvn deploy -P release
    #   env:
    #     GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
    #     GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
    #     OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
    #     OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
